### ISSUE TITLE
Why build an independent thing?

### ISSUE THREAD

**Issue by bydrei** [pestphp/pest-plugin-mutate#2]
Hello, I was at Laravel live at your talk.
Why not just build an "official" adapter in infection? They already have different adapters for different testing framework, as the maintainer of infection said [here](https://github.com/pestphp/pest/issues/4).

Not sure what the reasoning if behind the decision, but it's better to be united as a community than to go separate ways!? 

- They already have the community to keep the package up to date
- It's the only package as far I know in the PHP community for mutation testing, so having it in one place will be much better for the longer term as more people will contribute to improvements etc.

**Comment by gehrisandro** [comment]
Hi @bydrei 

Thanks for attending my talk yesterday.

As I already mentioned in my talk, the main reason is the deep integration into Pest, which wouldn't have been possible in the same way with Infection PHP.

P.S: Please use the discussions section if you have further questions.
